use std::fmt::Write;

use crate::analysis::{
    AnalysisLevel, CommunityConfig, CycleConfig, compute_hotspots, detect_communities, find_cycles,
    project_graph, tarjan_scc,
};
use crate::graph::Graph;
use crate::intelligence::detect_entrypoints;
use crate::model::NodeKind;

/// Configuration for architectural audit report generation.
#[derive(Debug, Clone)]
pub struct ReportConfig {
    pub top_hotspots_limit: usize,
    pub max_cycles_reported: usize,
    pub top_communities_limit: usize,
}

impl Default for ReportConfig {
    fn default() -> Self {
        Self {
            top_hotspots_limit: 10,
            max_cycles_reported: 5,
            top_communities_limit: 10,
        }
    }
}

/// Generate an executive architectural audit report in GitHub-flavored Markdown.
#[must_use]
pub fn generate_graph_report(graph: &Graph, config: &ReportConfig) -> String {
    let mut out = String::new();

    let mut file_count = 0;
    let mut symbol_count = 0;
    let mut lang_counts: std::collections::BTreeMap<&'static str, usize> =
        std::collections::BTreeMap::new();

    for n in &graph.nodes {
        if n.kind == NodeKind::File {
            file_count += 1;
        } else {
            symbol_count += 1;
        }
        if let Some(l) = n.language {
            *lang_counts.entry(l.as_str()).or_insert(0) += 1;
        }
    }

    let projected_mod = project_graph(graph, AnalysisLevel::Module, None);
    let mod_adj = projected_mod.to_adjacency();

    let hotspots = compute_hotspots(&mod_adj);
    let sccs = tarjan_scc(&mod_adj);
    let non_trivial_sccs: Vec<_> = sccs.iter().filter(|s| !s.is_trivial).collect();
    let cycles = find_cycles(&mod_adj, CycleConfig::default());
    let communities = detect_communities(&mod_adj, CommunityConfig::default());
    let entrypoints = detect_entrypoints(graph);

    let _ = writeln!(out, "# Graphia Architectural Audit Report\n");
    let _ = writeln!(
        out,
        "> Generated by **Graphia** — Native Code Graph & Repository Intelligence Engine.\n"
    );

    // 1. Executive Summary
    let _ = writeln!(out, "## 1. Executive Summary\n");
    let _ = writeln!(out, "| Metric | Value |");
    let _ = writeln!(out, "|---|---|");
    let _ = writeln!(out, "| **Total Graph Nodes** | {} |", graph.node_count());
    let _ = writeln!(out, "| **Total Relationships** | {} |", graph.edge_count());
    let _ = writeln!(out, "| **Source Files** | {file_count} |");
    let _ = writeln!(out, "| **Extracted Symbols** | {symbol_count} |");
    let _ = writeln!(out, "| **Distinct Modules** | {} |", mod_adj.node_count());
    let _ = writeln!(
        out,
        "| **Identified Entrypoints** | {} |",
        entrypoints.len()
    );
    let _ = writeln!(out, "| **Circular Dependency Cycles** | {} |", cycles.len());
    let _ = writeln!(
        out,
        "| **Detected Communities** | {} |\n",
        communities.len()
    );

    if !lang_counts.is_empty() {
        let _ = writeln!(out, "### Language Distribution\n");
        for (lang, count) in &lang_counts {
            let _ = writeln!(out, "- **{lang}**: {count} entities");
        }
        let _ = writeln!(out);
    }

    // 2. God Nodes & Architectural Hotspots
    let _ = writeln!(out, "## 2. God Nodes & Critical Hotspots\n");
    let _ = writeln!(
        out,
        "Components exhibiting disproportionately high centrality, incoming dependencies, and potential blast radius risk:\n"
    );

    let top_hotspots: Vec<_> = hotspots.iter().take(config.top_hotspots_limit).collect();
    if top_hotspots.is_empty() {
        let _ = writeln!(out, "_No critical hotspots detected._\n");
    } else {
        let _ = writeln!(
            out,
            "| Rank | Module / Entity | Score | Fan-In | Fan-Out | PageRank | In SCC |"
        );
        let _ = writeln!(out, "|---|---|---|---|---|---|---|");
        for (i, h) in top_hotspots.iter().enumerate() {
            let scc_badge = if h.in_scc { "⚠️ Yes" } else { "No" };
            let _ = writeln!(
                out,
                "| {} | `{}` | {:.2} | {} | {} | {:.4} | {} |",
                i + 1,
                h.id,
                h.score,
                h.fan_in,
                h.fan_out,
                h.pagerank,
                scc_badge
            );
        }
        let _ = writeln!(out);
    }

    // 3. Structural Cycles & Coupling Risks
    let _ = writeln!(out, "## 3. Coupling & Cycle Risks\n");
    if cycles.is_empty() && non_trivial_sccs.is_empty() {
        let _ = writeln!(
            out,
            "✅ **Clean Architecture**: No circular dependency cycles or mutually recursive SCCs detected.\n"
        );
    } else {
        let _ = writeln!(
            out,
            "⚠️ **Warning**: Found {} circular cycle(s) across {} non-trivial SCC cluster(s).\n",
            cycles.len(),
            non_trivial_sccs.len()
        );

        for (i, c) in cycles.iter().take(config.max_cycles_reported).enumerate() {
            let _ = writeln!(
                out,
                "- **Cycle #{}** (length {}): `{}`",
                i + 1,
                c.length,
                c.path.join(" -> ")
            );
        }
        if cycles.len() > config.max_cycles_reported {
            let _ = writeln!(
                out,
                "_... and {} additional cycles._",
                cycles.len() - config.max_cycles_reported
            );
        }
        let _ = writeln!(out);
    }

    // 4. Communities & Subsystem Clustering
    let _ = writeln!(out, "## 4. Subsystems & Community Clusters\n");
    if communities.is_empty() {
        let _ = writeln!(out, "_No distinct modular communities formed._\n");
    } else {
        for (i, comm) in communities
            .iter()
            .take(config.top_communities_limit)
            .enumerate()
        {
            let _ = writeln!(
                out,
                "### Subsystem Cluster #{} ({} members)",
                i + 1,
                comm.members.len()
            );
            let sample_members: Vec<_> = comm
                .members
                .iter()
                .take(8)
                .map(|s| format!("`{s}`"))
                .collect();
            let _ = writeln!(out, "Key members: {}\n", sample_members.join(", "));
        }
    }

    // 5. Entrypoints
    let _ = writeln!(out, "## 5. Discovered Entrypoints\n");
    if entrypoints.is_empty() {
        let _ = writeln!(out, "_No standard application entrypoints identified._\n");
    } else {
        for ep in &entrypoints {
            let _ = writeln!(
                out,
                "- [{:?}] `{}` (`{}:{}`)",
                ep.kind, ep.node.qualified_name, ep.node.location.file, ep.node.location.start_line
            );
        }
        let _ = writeln!(out);
    }

    // 6. Guidelines for Coding Agents
    let _ = writeln!(out, "## 6. AI Agent Guidelines & Safety Guardrails\n");
    let _ = writeln!(
        out,
        "1. **Tread Carefully on God Nodes**: Modifying symbols in the top hotspots carries high regression risk. Always query `graphia impact` or use `graphia explore` first."
    );
    let _ = writeln!(
        out,
        "2. **Circular Dependencies**: Refrain from adding new cross-module dependencies to cycles identified in Section 3."
    );
    let _ = writeln!(
        out,
        "3. **Context Optimization**: Use `graphia context --budget <tokens>` rather than reading full directories into LLM context."
    );

    out
}
